// flow-typed signature: 93c87d48038db4e4f2a1cc1f9db9d677
// flow-typed version: <<STUB>>/node_v8.9.4/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node/installArchSpecificPackage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node/installArchSpecificPackage.js' {
  declare module.exports: $Exports<'node/installArchSpecificPackage'>;
}
