// flow-typed signature: 578952dda7c93e27facf0e459ec5b2da
// flow-typed version: <<STUB>>/react-user-tour_v3.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-user-tour'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-user-tour' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-user-tour/dist/arrow-styles' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/arrow' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/arrows' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/helpers/arrow-styles' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/helpers/position-helpers' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/helpers/scroll-to-position' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/helpers/viewbox-helpers' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/index' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/position-helpers' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/tour-button-container' {
  declare module.exports: any;
}

declare module 'react-user-tour/dist/tour-button' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/arrow' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/helpers/arrow-styles' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/helpers/position-helpers' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/helpers/scroll-to-position' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/helpers/viewbox-helpers' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/index' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/tour-button-container' {
  declare module.exports: any;
}

declare module 'react-user-tour/src/tour-button' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-user-tour/dist/arrow-styles.js' {
  declare module.exports: $Exports<'react-user-tour/dist/arrow-styles'>;
}
declare module 'react-user-tour/dist/arrow.js' {
  declare module.exports: $Exports<'react-user-tour/dist/arrow'>;
}
declare module 'react-user-tour/dist/arrows.js' {
  declare module.exports: $Exports<'react-user-tour/dist/arrows'>;
}
declare module 'react-user-tour/dist/bundle.js' {
  declare module.exports: $Exports<'react-user-tour/dist/bundle'>;
}
declare module 'react-user-tour/dist/helpers/arrow-styles.js' {
  declare module.exports: $Exports<'react-user-tour/dist/helpers/arrow-styles'>;
}
declare module 'react-user-tour/dist/helpers/position-helpers.js' {
  declare module.exports: $Exports<'react-user-tour/dist/helpers/position-helpers'>;
}
declare module 'react-user-tour/dist/helpers/scroll-to-position.js' {
  declare module.exports: $Exports<'react-user-tour/dist/helpers/scroll-to-position'>;
}
declare module 'react-user-tour/dist/helpers/viewbox-helpers.js' {
  declare module.exports: $Exports<'react-user-tour/dist/helpers/viewbox-helpers'>;
}
declare module 'react-user-tour/dist/index.js' {
  declare module.exports: $Exports<'react-user-tour/dist/index'>;
}
declare module 'react-user-tour/dist/position-helpers.js' {
  declare module.exports: $Exports<'react-user-tour/dist/position-helpers'>;
}
declare module 'react-user-tour/dist/tour-button-container.js' {
  declare module.exports: $Exports<'react-user-tour/dist/tour-button-container'>;
}
declare module 'react-user-tour/dist/tour-button.js' {
  declare module.exports: $Exports<'react-user-tour/dist/tour-button'>;
}
declare module 'react-user-tour/src/arrow.js' {
  declare module.exports: $Exports<'react-user-tour/src/arrow'>;
}
declare module 'react-user-tour/src/helpers/arrow-styles.js' {
  declare module.exports: $Exports<'react-user-tour/src/helpers/arrow-styles'>;
}
declare module 'react-user-tour/src/helpers/position-helpers.js' {
  declare module.exports: $Exports<'react-user-tour/src/helpers/position-helpers'>;
}
declare module 'react-user-tour/src/helpers/scroll-to-position.js' {
  declare module.exports: $Exports<'react-user-tour/src/helpers/scroll-to-position'>;
}
declare module 'react-user-tour/src/helpers/viewbox-helpers.js' {
  declare module.exports: $Exports<'react-user-tour/src/helpers/viewbox-helpers'>;
}
declare module 'react-user-tour/src/index.js' {
  declare module.exports: $Exports<'react-user-tour/src/index'>;
}
declare module 'react-user-tour/src/tour-button-container.js' {
  declare module.exports: $Exports<'react-user-tour/src/tour-button-container'>;
}
declare module 'react-user-tour/src/tour-button.js' {
  declare module.exports: $Exports<'react-user-tour/src/tour-button'>;
}
