// flow-typed signature: 80f9c0703c297f9259c4f4c6c0ca2a7e
// flow-typed version: <<STUB>>/react-map-gl_v3.2.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-map-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-map-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-map-gl/dist/components/base-control' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/components/interactive-map' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/components/marker' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/components/navigation-control' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/components/popup' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/components/static-map' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/config' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/mapbox/mapbox' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/canvas-overlay' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/html-overlay' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/svg-overlay' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/autobind' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/deprecate-warn' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/diff-styles' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/dynamic-position' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/globals' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/is-immutable-map' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/map-controls' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/map-state' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/style-utils' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/transition-manager' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/transition/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/transition/linear-interpolator' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/transition/transition-interpolator' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/transition/transition-utils' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/transition/viewport-fly-to-interpolator' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/components/base-control' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/components/interactive-map' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/components/marker' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/components/navigation-control' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/components/popup' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/components/static-map' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/config' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/mapbox/mapbox' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/canvas-overlay' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/html-overlay' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/svg-overlay' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/autobind' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/deprecate-warn' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/diff-styles' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/dynamic-position' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/globals' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/is-immutable-map' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/map-controls' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/map-state' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/style-utils' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/transition-manager' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/transition/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/transition/linear-interpolator' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/transition/transition-interpolator' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/transition/transition-utils' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/transition/viewport-fly-to-interpolator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-map-gl/dist/components/base-control.js' {
  declare module.exports: $Exports<'react-map-gl/dist/components/base-control'>;
}
declare module 'react-map-gl/dist/components/interactive-map.js' {
  declare module.exports: $Exports<'react-map-gl/dist/components/interactive-map'>;
}
declare module 'react-map-gl/dist/components/marker.js' {
  declare module.exports: $Exports<'react-map-gl/dist/components/marker'>;
}
declare module 'react-map-gl/dist/components/navigation-control.js' {
  declare module.exports: $Exports<'react-map-gl/dist/components/navigation-control'>;
}
declare module 'react-map-gl/dist/components/popup.js' {
  declare module.exports: $Exports<'react-map-gl/dist/components/popup'>;
}
declare module 'react-map-gl/dist/components/static-map.js' {
  declare module.exports: $Exports<'react-map-gl/dist/components/static-map'>;
}
declare module 'react-map-gl/dist/config.js' {
  declare module.exports: $Exports<'react-map-gl/dist/config'>;
}
declare module 'react-map-gl/dist/index.js' {
  declare module.exports: $Exports<'react-map-gl/dist/index'>;
}
declare module 'react-map-gl/dist/mapbox/mapbox.js' {
  declare module.exports: $Exports<'react-map-gl/dist/mapbox/mapbox'>;
}
declare module 'react-map-gl/dist/overlays/canvas-overlay.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/canvas-overlay'>;
}
declare module 'react-map-gl/dist/overlays/html-overlay.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/html-overlay'>;
}
declare module 'react-map-gl/dist/overlays/svg-overlay.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/svg-overlay'>;
}
declare module 'react-map-gl/dist/utils/autobind.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/autobind'>;
}
declare module 'react-map-gl/dist/utils/deprecate-warn.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/deprecate-warn'>;
}
declare module 'react-map-gl/dist/utils/diff-styles.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/diff-styles'>;
}
declare module 'react-map-gl/dist/utils/dynamic-position.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/dynamic-position'>;
}
declare module 'react-map-gl/dist/utils/globals.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/globals'>;
}
declare module 'react-map-gl/dist/utils/is-immutable-map.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/is-immutable-map'>;
}
declare module 'react-map-gl/dist/utils/map-controls.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/map-controls'>;
}
declare module 'react-map-gl/dist/utils/map-state.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/map-state'>;
}
declare module 'react-map-gl/dist/utils/style-utils.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/style-utils'>;
}
declare module 'react-map-gl/dist/utils/transition-manager.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/transition-manager'>;
}
declare module 'react-map-gl/dist/utils/transition/index.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/transition/index'>;
}
declare module 'react-map-gl/dist/utils/transition/linear-interpolator.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/transition/linear-interpolator'>;
}
declare module 'react-map-gl/dist/utils/transition/transition-interpolator.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/transition/transition-interpolator'>;
}
declare module 'react-map-gl/dist/utils/transition/transition-utils.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/transition/transition-utils'>;
}
declare module 'react-map-gl/dist/utils/transition/viewport-fly-to-interpolator.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/transition/viewport-fly-to-interpolator'>;
}
declare module 'react-map-gl/src/components/base-control.js' {
  declare module.exports: $Exports<'react-map-gl/src/components/base-control'>;
}
declare module 'react-map-gl/src/components/interactive-map.js' {
  declare module.exports: $Exports<'react-map-gl/src/components/interactive-map'>;
}
declare module 'react-map-gl/src/components/marker.js' {
  declare module.exports: $Exports<'react-map-gl/src/components/marker'>;
}
declare module 'react-map-gl/src/components/navigation-control.js' {
  declare module.exports: $Exports<'react-map-gl/src/components/navigation-control'>;
}
declare module 'react-map-gl/src/components/popup.js' {
  declare module.exports: $Exports<'react-map-gl/src/components/popup'>;
}
declare module 'react-map-gl/src/components/static-map.js' {
  declare module.exports: $Exports<'react-map-gl/src/components/static-map'>;
}
declare module 'react-map-gl/src/config.js' {
  declare module.exports: $Exports<'react-map-gl/src/config'>;
}
declare module 'react-map-gl/src/index.js' {
  declare module.exports: $Exports<'react-map-gl/src/index'>;
}
declare module 'react-map-gl/src/mapbox/mapbox.js' {
  declare module.exports: $Exports<'react-map-gl/src/mapbox/mapbox'>;
}
declare module 'react-map-gl/src/overlays/canvas-overlay.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/canvas-overlay'>;
}
declare module 'react-map-gl/src/overlays/html-overlay.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/html-overlay'>;
}
declare module 'react-map-gl/src/overlays/svg-overlay.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/svg-overlay'>;
}
declare module 'react-map-gl/src/utils/autobind.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/autobind'>;
}
declare module 'react-map-gl/src/utils/deprecate-warn.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/deprecate-warn'>;
}
declare module 'react-map-gl/src/utils/diff-styles.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/diff-styles'>;
}
declare module 'react-map-gl/src/utils/dynamic-position.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/dynamic-position'>;
}
declare module 'react-map-gl/src/utils/globals.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/globals'>;
}
declare module 'react-map-gl/src/utils/is-immutable-map.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/is-immutable-map'>;
}
declare module 'react-map-gl/src/utils/map-controls.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/map-controls'>;
}
declare module 'react-map-gl/src/utils/map-state.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/map-state'>;
}
declare module 'react-map-gl/src/utils/style-utils.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/style-utils'>;
}
declare module 'react-map-gl/src/utils/transition-manager.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/transition-manager'>;
}
declare module 'react-map-gl/src/utils/transition/index.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/transition/index'>;
}
declare module 'react-map-gl/src/utils/transition/linear-interpolator.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/transition/linear-interpolator'>;
}
declare module 'react-map-gl/src/utils/transition/transition-interpolator.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/transition/transition-interpolator'>;
}
declare module 'react-map-gl/src/utils/transition/transition-utils.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/transition/transition-utils'>;
}
declare module 'react-map-gl/src/utils/transition/viewport-fly-to-interpolator.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/transition/viewport-fly-to-interpolator'>;
}
