const FallTypes = {
  FETCH_FALL_TIMING_OBJECT: 'FETCH_FALL_TIMING_OBJECT',
  REMOVE_FALL_TIMING_OBJECT: 'REMOVE_FALL_TIMING_OBJECT',

  FETCH_FALL_MAGNITUDE_OBJECT: 'FETCH_FALL_MAGNITUDE_OBJECT',
  REMOVE_FALL_MAGNITUDE_OBJECT: 'REMOVE_FALL_MAGNITUDE_OBJECT',

  FETCH_FALL_TIMING_WET_OBJECT: 'FETCH_FALL_TIMING_WET_OBJECT',
  REMOVE_FALL_TIMING_WET_OBJECT: 'REMOVE_FALL_TIMING_WET_OBJECT',

  FETCH_FALL_DURATION_OBJECT: 'FETCH_FALL_DURATION_OBJECT',
  REMOVE_FALL_DURATION_OBJECT: 'REMOVE_FALL_DURATION_OBJECT',
};

export default FallTypes;
