const FallTypes = {
  FETCH_FALL_TIMING_BP_OBJECT: 'FETCH_FALL_TIMING_BP_OBJECT',
  REMOVE_FALL_TIMING_BP_OBJECT: 'REMOVE_FALL_TIMING_BP_OBJECT',

  FETCH_FALL_MAGNITUDE_BP_OBJECT: 'FETCH_FALL_MAGNITUDE_BP_OBJECT',
  REMOVE_FALL_MAGNITUDE_BP_OBJECT: 'REMOVE_FALL_MAGNITUDE_BP_OBJECT',

  FETCH_FALL_TIMING_WET_BP_OBJECT: 'FETCH_FALL_TIMING_WET_BP_OBJECT',
  REMOVE_FALL_TIMING_WET_BP_OBJECT: 'REMOVE_FALL_TIMING_WET_BP_OBJECT',
};

export default FallTypes;
