const MetricDetailTypes = {
  FETCH_ALL_CLASS_BOX_PLOT_OBJECTS: 'FETCH_ALL_CLASS_BOX_PLOT_OBJECTS',
  UPDATE_LOADING_OBJECT: 'UPDATE_LOADING_OBJECT',
  FETCH_ANNUAL_FLOW_OBJECT: 'FETCH_ANNUAL_FLOW_OBJECT',
  TOGGLE_DRAWER_OBJECT: 'TOGGLE_DRAWER_OBJECT',
};

export default MetricDetailTypes;
