const SpringTypes = {
  FETCH_SPRING_TIMING_OBJECT: 'FETCH_SPRING_TIMING_OBJECT',
  REMOVE_SPRING_TIMING_OBJECT: 'REMOVE_SPRING_TIMING_OBJECT',

  FETCH_SPRING_MAGNITUDE_OBJECT: 'FETCH_SPRING_MAGNITUDE_OBJECT',
  REMOVE_SPRING_MAGNITUDE_OBJECT: 'REMOVE_SPRING_MAGNITUDE_OBJECT',

  FETCH_SPRING_RATE_OF_CHANGE_OBJECT: 'FETCH_SPRING_RATE_OF_CHANGE_OBJECT',
  REMOVE_SPRING_RATE_OF_CHANGE_OBJECT: 'REMOVE_SPRING_RATE_OF_CHANGE_OBJECT',

  FETCH_SPRING_DURATION_OBJECT: 'FETCH_SPRING_DURATION_OBJECT',
  REMOVE_SPRING_DURATION_OBJECT: 'REMOVE_SPRING_DURATION_OBJECT',
};

export default SpringTypes;
