const SummerTypes = {
  FETCH_SUMMER_TIMING_BP_OBJECT: 'FETCH_SUMMER_TIMING_BP_OBJECT',
  REMOVE_SUMMER_TIMING_BP_OBJECT: 'REMOVE_SUMMER_TIMING_BP_OBJECT',

  FETCH_SUMMER_MAGNITUDE_10_BP_OBJECT: 'FETCH_SUMMER_MAGNITUDE_10_BP_OBJECT',
  REMOVE_SUMMER_MAGNITUDE_10_BP_OBJECT: 'REMOVE_SUMMER_MAGNITUDE_10_BP_OBJECT',

  FETCH_SUMMER_MAGNITUDE_50_BP_OBJECT: 'FETCH_SUMMER_MAGNITUDE_50_BP_OBJECT',
  REMOVE_SUMMER_MAGNITUDE_50_BP_OBJECT: 'REMOVE_SUMMER_MAGNITUDE_50_BP_OBJECT',
};

export default SummerTypes;
