const SummerTypes = {
  FETCH_SUMMER_TIMING_OBJECT: 'FETCH_SUMMER_TIMING_OBJECT',
  REMOVE_SUMMER_TIMING_OBJECT: 'REMOVE_SUMMER_TIMING_OBJECT',

  FETCH_SUMMER_MAGNITUDE_10_OBJECT: 'FETCH_SUMMER_MAGNITUDE_10_OBJECT',
  REMOVE_SUMMER_MAGNITUDE_10_OBJECT: 'REMOVE_SUMMER_MAGNITUDE_10_OBJECT',

  FETCH_SUMMER_MAGNITUDE_50_OBJECT: 'FETCH_SUMMER_MAGNITUDE_50_OBJECT',
  REMOVE_SUMMER_MAGNITUDE_50_OBJECT: 'REMOVE_SUMMER_MAGNITUDE_50_OBJECT',

  FETCH_SUMMER_DURATION_FLUSH_OBJECT: 'FETCH_SUMMER_DURATION_FLUSH_OBJECT',
  REMOVE_SUMMER_DURATION_FLUSH_OBJECT: 'REMOVE_SUMMER_DURATION_FLUSH_OBJECT',

  FETCH_SUMMER_DURATION_WET_OBJECT: 'FETCH_SUMMER_DURATION_WET_OBJECT',
  REMOVE_SUMMER_DURATION_WET_OBJECT: 'REMOVE_SUMMER_DURATION_WET_OBJECT',

  FETCH_SUMMER_NO_FLOW_COUNTS_OBJECT: 'FETCH_SUMMER_NO_FLOW_COUNTS_OBJECT',
  REMOVE_SUMMER_NO_FLOW_COUNTS_OBJECT: 'REMOVE_SUMMER_NO_FLOW_COUNTS_OBJECT',
};

export default SummerTypes;
