const UserTypes = {
  FETCH_BROADCAST_MESSAGE: "FETCH_BROADCAST_MESSAGE",
  SUBMIT_BUG_REPORT_OBJECT: "SUBMIT_BUG_REPORT_OBJECT",
  USER_LOGIN_OBJECT: "USER_LOGIN_OBJECT",
  REMOVE_USER_OBJECT: "REMOVE_USER_OBJECT",
};

export default UserTypes;
