const WinterTypes = {
  FETCH_WINTER_MAGNITUDE_2_BP_OBJECT: 'FETCH_WINTER_MAGNITUDE_2_BP_OBJECT',
  REMOVE_WINTER_MAGNITUDE_2_BP_OBJECT: 'REMOVE_WINTER_MAGNITUDE_2_BP_OBJECT',

  FETCH_WINTER_MAGNITUDE_5_BP_OBJECT: 'FETCH_WINTER_MAGNITUDE_5_BP_OBJECT',
  REMOVE_WINTER_MAGNITUDE_5_BP_OBJECT: 'REMOVE_WINTER_MAGNITUDE_5_BP_OBJECT',

  FETCH_WINTER_MAGNITUDE_10_BP_OBJECT: 'FETCH_WINTER_MAGNITUDE_10_BP_OBJECT',
  REMOVE_WINTER_MAGNITUDE_10_BP_OBJECT: 'REMOVE_WINTER_MAGNITUDE_10_BP_OBJECT',

  FETCH_WINTER_MAGNITUDE_20_BP_OBJECT: 'FETCH_WINTER_MAGNITUDE_20_BP_OBJECT',
  REMOVE_WINTER_MAGNITUDE_20_BP_OBJECT: 'REMOVE_WINTER_MAGNITUDE_20_BP_OBJECT',

  FETCH_WINTER_MAGNITUDE_50_BP_OBJECT: 'FETCH_WINTER_MAGNITUDE_50_BP_OBJECT',
  REMOVE_WINTER_MAGNITUDE_50_BP_OBJECT: 'REMOVE_WINTER_MAGNITUDE_50_BP_OBJECT',
};

export default WinterTypes;
